更新 sing-box 脚本
- 新增订阅合并功能
- 优化安装脚本，保留备份原配置文件
- 同步更新文档

diff --git a/patch/sing-box/ucode/iptables/sing-box.init b/patch/sing-box/ucode/iptables/sing-box.init
--- a/patch/sing-box/ucode/iptables/sing-box.init
+++ b/patch/sing-box/ucode/iptables/sing-box.init
@@ -6,56 +6,44 @@ USE_PROCD=1
 PROG="/usr/bin/sing-box"
 
 DNSMASQ_UCI_CONFIG=$(uci -q show "dhcp.@dnsmasq[0]" | awk 'NR==1 {split($0, conf, /[.=]/); print conf[2]}')
-if [ -f "/tmp/etc/dnsmasq.conf.$DNSMASQ_UCI_CONFIG" ]; then
+if [ -e "/tmp/etc/dnsmasq.conf.$DNSMASQ_UCI_CONFIG" ]; then
     DNSMASQ_DIR="$(awk -F '=' '/^conf-dir=/ {print $2}' "/tmp/etc/dnsmasq.conf.$DNSMASQ_UCI_CONFIG")/dnsmasq-sing.d"
 else
     DNSMASQ_DIR="/tmp/dnsmasq.d/dnsmasq-sing.d"
 fi
+
+extra_command 'update_subscription' ' Update subscription file'
 
 start_service() {
     config_load sing-box
 
     local enabled
     config_get_bool enabled "main" "enabled" 0
-    if [ "$enabled" = 1 ]; then
-        echo "[ sing-box ] Enabled."
-        echo "[ sing-box ] Start."
-    else
-        echo "[ sing-box ] Disabled."
-        echo "[ sing-box ] Exit."
-        return
-    fi
+    [ "$enabled" = 1 ] || return
 
-    local workdir remote url auto_restart restart_cron
+    local workdir conf restart_cron
     config_get workdir "main" "workdir" "/etc/sing-box"
-    config_get remote "subscription" "remote" 1
-    config_get url "subscription" "url"
-    config_get_bool auto_restart "subscription" "auto_restart" 1
-    config_get restart_cron "subscription" "restart_cron" "0 5 * * *"
+    config_get conf "profile" "conf"
+    config_get restart_cron "profile" "restart_cron" "0 5 * * *"
 
-    if [ "$remote" -gt 0 ] && [ -n "$url" ]; then
-        echo "[ sing-box ] Start update subscription."
-        update_subscription
-        if [ ! -f "$workdir/profiles/subscription$remote.json" ]; then
-            echo "[ sing-box ] Subscription $remote is not found."
-            echo "[ sing-box ] Exit."
+    update_subscription
+
+    local a=1
+    for i in $conf; do
+        if [ "${i#file:}" != "$i" ] && [ ! -e "$workdir/profiles/${i#file:}" ]; then
+            echo -e "\033[1;31mError:\033[0m ${i#file:} is not found. Exit!"
+            return
+        elif [ ! -f "$workdir/profiles/$(echo -n $i | md5sum | awk '{print $1}')" ]; then
+            echo -e "\033[1;31mError:\033[0m subscription $a is not found. Exit!"
             return
         fi
-    elif [ "$remote" = 0 ] && [ ! -f "$workdir/profiles/sing-box.json" ]; then
-        echo "[ sing-box ] File is not found."
-        echo "[ sing-box ] Exit."
-        return
-    fi
+        a=$((a + 1))
+    done
 
     ucode -S $workdir/scripts/generate_config.uc
-    if [ -f "$workdir/run/config.json" ]; then
-        echo "[ sing-box ] Generate configuration successful."
-    else
-        echo "[ sing-box ] Generate configuration failed."
-    fi
 
     local dns_port
-    config_get dns_port "inbounds" "dns_port" "2053"
+    config_get dns_port "basic" "dns_port" "2053"
     mkdir -p $DNSMASQ_DIR
     echo -e "conf-dir=$DNSMASQ_DIR" > $DNSMASQ_DIR/../dnsmasq-sing.conf
     cat <<-EOF >> $DNSMASQ_DIR/redirect-dns.conf
@@ -76,7 +64,7 @@ EOF
     procd_set_param file "$workdir/run/config.json"
     procd_set_param limits core="unlimited"
     procd_set_param limits nofile="1000000 1000000"
-    procd_set_param stdout 1
+    procd_set_param stdout 0
     procd_set_param stderr 1
     procd_set_param respawn
 
@@ -85,19 +73,9 @@ EOF
     ip rule add fwmark 1 table 100
     ip route add local 0.0.0.0/0 dev lo table 100
 
-    local lan_addr redirect tproxy output
+    local lan_addr
     lan_addr=$(ip a | grep -w inet | grep brd | grep "`uci get network.lan.device`" | awk '{print $2}')
     utpl -S -D lan_addr="$lan_addr" $workdir/scripts/firewall_post.ut | sh -
-    if iptables -t nat -L sing_redirect -n >/dev/null 2>&1; then redirect='success'; fi
-    if iptables -t mangle -L sing_tproxy -n >/dev/null 2>&1; then tproxy='success'; fi
-    if iptables -t mangle -L sing_tproxy_output -n >/dev/null 2>&1; then output='success'; fi
-    if [ "$redirect" = "success" ] && [ "$tproxy" = "success" ] && [ "$output" = "success" ]; then
-        echo "[ sing-box ] Set firewall successful."
-    else
-        echo "[ sing-box ] Set firewall failed."
-        echo "[ sing-box ] Exit."
-        return
-    fi
 
     local bridge_nf_call_iptables
     bridge_nf_call_iptables=$(sysctl -e -n net.bridge.bridge-nf-call-iptables)
@@ -106,22 +84,19 @@ EOF
         sysctl -q -w net.bridge.bridge-nf-call-iptables=0
     fi
 
-    if [ "$auto_restart" = "1" ]; then
-    echo "[ sing-box ] Set scheduled restart."
+    if [ -n "$restart_cron" ]; then
         sed -i '/sing-box/d' /etc/crontabs/root
         echo -e "$restart_cron /etc/init.d/sing-box restart" >> /etc/crontabs/root
         /etc/init.d/cron restart
     fi
-
-    echo "[ sing-box ] Started."
 }
 
 stop_service() {
     config_load sing-box
 
-    local output
-    config_get output "log" "output" "/var/log/sing-box.log"
-    rm -f $output
+    local log_file
+    config_get log_file "basic" "log_file"
+    [ -n "$log_file" ] && rm -f $log_file
 
     ip rule del fwmark 1 table 100 2>/dev/null
     ip route del local 0.0.0.0/0 dev lo table 100 2>/dev/null
@@ -145,9 +120,7 @@ stop_service() {
     rm -rf $DNSMASQ_DIR/../dnsmasq-sing.conf $DNSMASQ_DIR
     /etc/init.d/dnsmasq restart 2>/dev/null
 
-    local workdir
-    config_get workdir "main" "workdir" "/etc/sing-box"
-    if [ -f /var/run/br_netfilter.flag ]; then
+    if [ -f "/var/run/br_netfilter.flag" ]; then
         rm -f /var/run/br_netfilter.flag
         sysctl -q -w net.bridge.bridge-nf-call-iptables=1
     fi
@@ -159,23 +132,19 @@ stop_service() {
 update_subscription () {
     config_load sing-box
 
-    local a workdir remote update_all url
+    local workdir conf
     config_get workdir "main" "workdir" "/etc/sing-box"
-    config_get remote "subscription" "remote" 1
-    config_get_bool update_all "subscription" "update_all" 0
-    config_get url "subscription" "url"
+    config_get conf "profile" "conf"
 
-    a=1
-    for i in $url; do
-        if [ "$update_all" = "1" ] || [ "$remote" = "$a" ]; then
-            curl -fsL -A sing-box -m 120 --connect-timeout 15 --retry 3 -X GET -o $workdir/profiles/config.tmp $i
-            if [ -f "$workdir/profiles/config.tmp" ]; then
-                echo "[ sing-box ] Subscription $a download successful."
-                mv $workdir/profiles/config.tmp $workdir/profiles/subscription$a.json
+    local a=1
+    for i in $conf; do
+        if [ "${i#file:}" = "$i" ]; then
+            if curl -fsL -A sing-box -m 120 --connect-timeout 15 --retry 3 -X GET -o $workdir/profiles/config.tmp $i > /dev/null 2>&1; then
+                mv $workdir/profiles/config.tmp "$workdir/profiles/$(echo -n $i | md5sum | awk '{print $1}')"
             else
-                echo "[ sing-box ] Subscription $a download failed."
+                echo -e "\033[1;33mWarning:\033[0m subscription $a download failed."
             fi
         fi
-        let a++
+        a=$((a + 1))
     done
 }
