update

diff --git a/patch/sing-box/ucode/iptables/sing-box.init b/patch/sing-box/ucode/iptables/sing-box.init
--- a/patch/sing-box/ucode/iptables/sing-box.init
+++ b/patch/sing-box/ucode/iptables/sing-box.init
@@ -17,45 +17,29 @@ start_service() {
 
     local enabled
     config_get_bool enabled "main" "enabled" 0
-    if [ "$enabled" = 1 ]; then
-        echo "[ sing-box ] Enabled."
-        echo "[ sing-box ] Start."
-    else
-        echo "[ sing-box ] Disabled."
-        echo "[ sing-box ] Exit."
-        return
-    fi
+    [ "$enabled" = 1 ] || return
 
-    local workdir remote url auto_restart restart_cron
+    local workdir profile url restart_cron
     config_get workdir "main" "workdir" "/etc/sing-box"
-    config_get remote "subscription" "remote" 1
-    config_get url "subscription" "url"
-    config_get_bool auto_restart "subscription" "auto_restart" 1
-    config_get restart_cron "subscription" "restart_cron" "0 5 * * *"
+    config_get profile "profile" "profile" "sub:1"
+    config_get url "profile" "url"
+    config_get restart_cron "profile" "restart_cron" "0 5 * * *"
 
-    if [ "$remote" -gt 0 ] && [ -n "$url" ]; then
-        echo "[ sing-box ] Start update subscription."
+    if [ "$profile" = "^sub:*" ] && [ -n "$url" ]; then
         update_subscription
-        if [ ! -f "$workdir/profiles/subscription$remote.json" ]; then
-            echo "[ sing-box ] Subscription $remote is not found."
-            echo "[ sing-box ] Exit."
+        if [ ! -f "$workdir/profiles/subscription${profile/sub:/}.json" ]; then
+            echo -e "\e[1;31mERROR\e[0m Subscription ${profile/sub:/} is not found. Exit"
             return
         fi
-    elif [ "$remote" = 0 ] && [ ! -f "$workdir/profiles/sing-box.json" ]; then
-        echo "[ sing-box ] File is not found."
-        echo "[ sing-box ] Exit."
+    elif [ "$profile" = "^file:*" ] && [ ! -f "$workdir/profiles/${profile/file:/}" ]; then
+        echo -e "\e[1;31mERROR\e[0m Profile is not found. Exit"
         return
     fi
 
     ucode -S $workdir/scripts/generate_config.uc
-    if [ -f "$workdir/run/config.json" ]; then
-        echo "[ sing-box ] Generate configuration successful."
-    else
-        echo "[ sing-box ] Generate configuration failed."
-    fi
 
     local dns_port
-    config_get dns_port "inbounds" "dns_port" "2053"
+    config_get dns_port "basic" "dns_port" "2053"
     mkdir -p $DNSMASQ_DIR
     echo -e "conf-dir=$DNSMASQ_DIR" > $DNSMASQ_DIR/../dnsmasq-sing.conf
     cat <<-EOF >> $DNSMASQ_DIR/redirect-dns.conf
@@ -85,19 +69,9 @@ EOF
     ip rule add fwmark 1 table 100
     ip route add local 0.0.0.0/0 dev lo table 100
 
-    local lan_addr redirect tproxy output
+    local lan_addr
     lan_addr=$(ip a | grep -w inet | grep brd | grep "`uci get network.lan.device`" | awk '{print $2}')
     utpl -S -D lan_addr="$lan_addr" $workdir/scripts/firewall_post.ut | sh -
-    if iptables -t nat -L sing_redirect -n >/dev/null 2>&1; then redirect='success'; fi
-    if iptables -t mangle -L sing_tproxy -n >/dev/null 2>&1; then tproxy='success'; fi
-    if iptables -t mangle -L sing_tproxy_output -n >/dev/null 2>&1; then output='success'; fi
-    if [ "$redirect" = "success" ] && [ "$tproxy" = "success" ] && [ "$output" = "success" ]; then
-        echo "[ sing-box ] Set firewall successful."
-    else
-        echo "[ sing-box ] Set firewall failed."
-        echo "[ sing-box ] Exit."
-        return
-    fi
 
     local bridge_nf_call_iptables
     bridge_nf_call_iptables=$(sysctl -e -n net.bridge.bridge-nf-call-iptables)
@@ -106,22 +80,19 @@ EOF
         sysctl -q -w net.bridge.bridge-nf-call-iptables=0
     fi
 
-    if [ "$auto_restart" = "1" ]; then
-    echo "[ sing-box ] Set scheduled restart."
+    if [ -n "$restart_cron" ]; then
         sed -i '/sing-box/d' /etc/crontabs/root
         echo -e "$restart_cron /etc/init.d/sing-box restart" >> /etc/crontabs/root
         /etc/init.d/cron restart
     fi
-
-    echo "[ sing-box ] Started."
 }
 
 stop_service() {
     config_load sing-box
 
-    local output
-    config_get output "log" "output" "/var/log/sing-box.log"
-    rm -f $output
+    local log_file
+    config_get log_file "basic" "log_file"
+    [ -n "$log_file" ] && rm -f $log_file
 
     ip rule del fwmark 1 table 100 2>/dev/null
     ip route del local 0.0.0.0/0 dev lo table 100 2>/dev/null
@@ -159,21 +130,19 @@ stop_service() {
 update_subscription () {
     config_load sing-box
 
-    local a workdir remote update_all url
+    local a workdir profile url
     config_get workdir "main" "workdir" "/etc/sing-box"
-    config_get remote "subscription" "remote" 1
-    config_get_bool update_all "subscription" "update_all" 0
-    config_get url "subscription" "url"
+    config_get profile "profile" "profile" "sub:1"
+    config_get url "profile" "url"
 
     a=1
     for i in $url; do
-        if [ "$update_all" = "1" ] || [ "$remote" = "$a" ]; then
+        if [ "$profile" = "all" ] || [ "${profile/sub:/}" = "$a" ]; then
             curl -fsL -A sing-box -m 120 --connect-timeout 15 --retry 3 -X GET -o $workdir/profiles/config.tmp $i
             if [ -f "$workdir/profiles/config.tmp" ]; then
-                echo "[ sing-box ] Subscription $a download successful."
                 mv $workdir/profiles/config.tmp $workdir/profiles/subscription$a.json
             else
-                echo "[ sing-box ] Subscription $a download failed."
+                echo -e "\e[1;33mWARN\e[0m Subscription $a download failed."
             fi
         fi
         let a++
